name: master
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run test

  # Add repository secret on GitHub
  publish:
    runs-on: ubuntu-latest
    # needs: [setup, lint, test]
    needs: [lint, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
